/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aplikasipenjualan;

/**
 *
 * @author Daffa fauzand
 */
public class OptionMenu extends javax.swing.JInternalFrame {

    /**
     * Creates new form OptionMenu
     */
    public OptionMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topaymentBtn = new javax.swing.JButton();
        sohowDataButton = new javax.swing.JButton();

        setTitle("OPTION MENU");

        topaymentBtn.setText("PENJUALAN RUMAH");
        topaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topaymentBtnActionPerformed(evt);
            }
        });

        sohowDataButton.setText("TAMPILKAN DATA");
        sohowDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sohowDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(topaymentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(sohowDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topaymentBtn)
                    .addComponent(sohowDataButton))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topaymentBtnActionPerformed
        PaymentForm paymentform = new PaymentForm();
        paymentform.setVisible(true);
        this.getDesktopPane().add(paymentform);
        this.dispose();
    }//GEN-LAST:event_topaymentBtnActionPerformed

    private void sohowDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sohowDataButtonActionPerformed
        DataForm dataform = new DataForm();
        dataform.setVisible(true);
        this.getDesktopPane().add(dataform);
        this.dispose();
    }//GEN-LAST:event_sohowDataButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton sohowDataButton;
    private javax.swing.JButton topaymentBtn;
    // End of variables declaration//GEN-END:variables
}
