/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package aplikasipenjualan;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Daffa fauzand
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form paymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButton = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        areacmb = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t36rbt = new javax.swing.JRadioButton();
        t45rbt = new javax.swing.JRadioButton();
        t54rbt = new javax.swing.JRadioButton();
        buildingPriceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        largeLandTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        availableLandTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalpriceTxt = new javax.swing.JTextField();
        dpTxt = new javax.swing.JTextField();
        lmcicilan = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        cicilan = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        setujucb = new javax.swing.JCheckBox();
        prosesbtn = new javax.swing.JButton();
        simpanbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah/m2");

        jLabel3.setText("Area");

        priceLandTxt.setEditable(false);
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        areacmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- PILIH ---", "BUGENVILE", "MELATI ", "PLAMBOYAN" }));
        areacmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areacmbActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplikasipenjualan/denah rumah1.jpg"))); // NOI18N

        jLabel5.setText("Harga Bangunan");

        jLabel6.setText("Tipe Rumah");

        radioButton.add(t36rbt);
        t36rbt.setText("Tipe - 36");
        t36rbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36rbtActionPerformed(evt);
            }
        });

        radioButton.add(t45rbt);
        t45rbt.setText("Tipe - 45");
        t45rbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t45rbtActionPerformed(evt);
            }
        });

        radioButton.add(t54rbt);
        t54rbt.setText("Tipe - 54");
        t54rbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t54rbtActionPerformed(evt);
            }
        });

        buildingPriceTxt.setEditable(false);
        buildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel7.setText("Luas Tanah Asli");

        largeLandTxt.setEditable(false);
        largeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel8.setText("Luas Tanah Tersedia");

        availableLandTxt.setEditable(false);
        availableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPn(10%)");

        jLabel13.setText("Cicilan / Bulan");

        totalpriceTxt.setEditable(false);
        totalpriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        dpTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lmcicilan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cicilan.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Bulan");

        setujucb.setText("Setuju");
        setujucb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setujucbActionPerformed(evt);
            }
        });

        prosesbtn.setText("PROSES");
        prosesbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesbtnActionPerformed(evt);
            }
        });

        simpanbtn.setText("SIMPAN");
        simpanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanbtnActionPerformed(evt);
            }
        });

        hapusbtn.setText("HAPUS");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(priceLandTxt)
                        .addComponent(orderNameTxt)
                        .addComponent(areacmb, 0, 140, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(t36rbt)
                    .addComponent(t45rbt)
                    .addComponent(t54rbt)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(prosesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buildingPriceTxt)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(largeLandTxt)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                            .addComponent(availableLandTxt)
                            .addComponent(totalpriceTxt)
                            .addComponent(dpTxt)
                            .addComponent(lmcicilan)
                            .addComponent(ppnTxt)
                            .addComponent(cicilan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(setujucb)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpanbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(areacmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t36rbt))
                    .addComponent(largeLandTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t45rbt)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t54rbt)
                            .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(totalpriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(dpTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lmcicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(setujucb))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prosesbtn)
                    .addComponent(simpanbtn)
                    .addComponent(hapusbtn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areacmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areacmbActionPerformed
        switch(areacmb.getSelectedIndex()){
            case 0:
                priceLandTxt.setText("");
                buildingPriceTxt.setText("");
                break;
                
            case 1:
                priceLandTxt.setText("500000");
                buildingPriceTxt.setText("90000000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                dpTxt.setText("");
                lmcicilan.setText("");
                cicilan.setText("");
                ppnTxt.setText("");
                totalpriceTxt.setText("");
                setujucb.setSelected(false);
                break;
            
            case 2:
                priceLandTxt.setText("600000");
                buildingPriceTxt.setText("120000000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                dpTxt.setText("");
                lmcicilan.setText("");
                cicilan.setText("");
                ppnTxt.setText("");
                totalpriceTxt.setText("");
                setujucb.setSelected(false);
                break;
                
            default:
                priceLandTxt.setText("700000");
                buildingPriceTxt.setText("150000000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                dpTxt.setText("");
                lmcicilan.setText("");
                cicilan.setText("");
                ppnTxt.setText("");
                totalpriceTxt.setText("");
                setujucb.setSelected(false);
                break;
        }
    }//GEN-LAST:event_areacmbActionPerformed

    private void t36rbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36rbtActionPerformed
        if(areacmb.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
            radioButton.clearSelection();
        } else {
            largeLandTxt.setText("90");
            availableLandTxt.setText("54");
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    totalPrice;
            totalPrice = (availableLand * landPrice )+ buildingPrice;
            totalpriceTxt.setText("" + totalPrice);
            
            lmcicilan.setText("");
            dpTxt.setText("");
            ppnTxt.setText("");
            cicilan.setText("");
        }
    }//GEN-LAST:event_t36rbtActionPerformed

    private void t45rbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t45rbtActionPerformed
        if(areacmb.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
            radioButton.clearSelection();
        } else {
            largeLandTxt.setText("120");
            availableLandTxt.setText("75");
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    totalPrice;
            totalPrice = (availableLand * landPrice )+ buildingPrice;
            totalpriceTxt.setText("" + totalPrice);
            
            dpTxt.setText("");
            ppnTxt.setText("");
            cicilan.setText("");
            lmcicilan.setText("");
        }
    }//GEN-LAST:event_t45rbtActionPerformed

    private void t54rbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t54rbtActionPerformed
        if(areacmb.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Pilih area terlebih dahulu");
            radioButton.clearSelection();
        } else {
            largeLandTxt.setText("140");
            availableLandTxt.setText("86");
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    totalPrice;
            totalPrice = (availableLand * landPrice )+ buildingPrice;
            totalpriceTxt.setText("" + totalPrice);
            
            dpTxt.setText("");
            ppnTxt.setText("");
            cicilan.setText("");
            lmcicilan.setText("");
        }
    }//GEN-LAST:event_t54rbtActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        orderNameTxt.setText("");
        priceLandTxt.setText("");
        buildingPriceTxt.setText("");
        largeLandTxt.setText("");
        availableLandTxt.setText("");
        dpTxt.setText("");
        lmcicilan.setText("");
        cicilan.setText("");
        ppnTxt.setText("");
        areacmb.setSelectedIndex(0);
        radioButton.clearSelection();
        setujucb.setSelected(false);
        totalpriceTxt.setText("");
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void prosesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesbtnActionPerformed
        if(totalpriceTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Pilihan belum lengkap");
        } else if(dpTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "DP belum diisi");
        } else if(lmcicilan.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Isi jumlah cicilan yang diinginkan");
        } else {
            long landPrice = Long.parseLong(priceLandTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    dp = Long.parseLong(dpTxt.getText()),
                    lamacicilan = Long.parseLong(lmcicilan.getText()),
                    totalPrice, ppn, instalmentPerMonth;
            totalPrice = (availableLand * landPrice) + buildingPrice;
            ppn = totalPrice * 10 / 100;
            instalmentPerMonth = (totalPrice + ppn) / lamacicilan;
            ppnTxt.setText("" + ppn);
            cicilan.setText("" + instalmentPerMonth);
         
        }
    }//GEN-LAST:event_prosesbtnActionPerformed

    private void setujucbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setujucbActionPerformed
        if(orderNameTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nama pemesan harus diisi");
            setujucb.setSelected(false);
        } else if( ppnTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Tekan tombol proses terlebih dahulu");
            setujucb.setSelected(false);
        } else if(setujucb.isSelected() == true){
            JOptionPane.showMessageDialog(null, "Pemesan menyetujui");
            setujucb.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(null, "Pemesan belum menyetujui");
            setujucb.setSelected(false);
        }   
    }//GEN-LAST:event_setujucbActionPerformed

    private void simpanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanbtnActionPerformed
        if(setujucb.isSelected() == false){
            JOptionPane.showMessageDialog(null, 
                    "Klik centang untuk simpan data", "Error", 
                    JOptionPane.ERROR_MESSAGE);
        } else {
            String typeHouse;
            if(t36rbt.isSelected()){
                typeHouse = "TIPE 36";
            } else if(t45rbt.isSelected()){
                typeHouse = "TIPE 45";
            } else {
                typeHouse = "TIPE 54";
            }
            
            
            try{
                String sql = "INSERT INTO rumah(name, area, tipe, luas, harga, jumlah_cicilan, cicilan_bulan) VALUES ('"
                        + orderNameTxt.getText() + "','"
                        + areacmb.getSelectedItem() + "','"
                        + typeHouse + "','"
                        + largeLandTxt.getText() + "','"
                        + totalpriceTxt.getText() + "','"
                        + lmcicilan.getText() + "','"
                        + cicilan.getText() + "')";
                Connection conn = (Connection)ConnectionDb.connectDatabase();
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);
                pst.execute();
            } catch (SQLException ex) {
                Logger.getLogger(PaymentForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            OptionMenu optionmenu = new OptionMenu();
            optionmenu.setVisible(true);
            this.getDesktopPane().add(optionmenu);
            this.dispose();
        }
    }//GEN-LAST:event_simpanbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> areacmb;
    private javax.swing.JTextField availableLandTxt;
    private javax.swing.JTextField buildingPriceTxt;
    private javax.swing.JTextField cicilan;
    private javax.swing.JTextField dpTxt;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField largeLandTxt;
    private javax.swing.JTextField lmcicilan;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton prosesbtn;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JCheckBox setujucb;
    private javax.swing.JButton simpanbtn;
    private javax.swing.JRadioButton t36rbt;
    private javax.swing.JRadioButton t45rbt;
    private javax.swing.JRadioButton t54rbt;
    private javax.swing.JTextField totalpriceTxt;
    // End of variables declaration//GEN-END:variables
}
